// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppGSL.h>
#include <Rcpp.h>

using namespace Rcpp;

// bernstein_poly_01_test2
void bernstein_poly_01_test2();
RcppExport SEXP _rblock_bernstein_poly_01_test2() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    bernstein_poly_01_test2();
    return R_NilValue;
END_RCPP
}
// resetGraph
void resetGraph();
RcppExport SEXP _rblock_resetGraph() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    resetGraph();
    return R_NilValue;
END_RCPP
}
// resetModel
void resetModel();
RcppExport SEXP _rblock_resetModel() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    resetModel();
    return R_NilValue;
END_RCPP
}
// deleteGraph
void deleteGraph();
RcppExport SEXP _rblock_deleteGraph() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    deleteGraph();
    return R_NilValue;
END_RCPP
}
// deleteModel
void deleteModel();
RcppExport SEXP _rblock_deleteModel() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    deleteModel();
    return R_NilValue;
END_RCPP
}
// print
void print(Rcpp::IntegerVector PRINT);
RcppExport SEXP _rblock_print(SEXP PRINTSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type PRINT(PRINTSEXP);
    print(PRINT);
    return R_NilValue;
END_RCPP
}
// loadGraph
void loadGraph(Rcpp::DataFrame DF, Rcpp::IntegerVector directed, Rcpp::IntegerVector names);
RcppExport SEXP _rblock_loadGraph(SEXP DFSEXP, SEXP directedSEXP, SEXP namesSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type DF(DFSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type directed(directedSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type names(namesSEXP);
    loadGraph(DF, directed, names);
    return R_NilValue;
END_RCPP
}
// printGraph
void printGraph();
RcppExport SEXP _rblock_printGraph() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    printGraph();
    return R_NilValue;
END_RCPP
}
// loadMetaData
void loadMetaData(Rcpp::DataFrame DF, Rcpp::IntegerVector MODELS);
RcppExport SEXP _rblock_loadMetaData(SEXP DFSEXP, SEXP MODELSSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type DF(DFSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type MODELS(MODELSSEXP);
    loadMetaData(DF, MODELS);
    return R_NilValue;
END_RCPP
}
// runDCSBM
void runDCSBM(Rcpp::IntegerVector K, Rcpp::IntegerVector SEED, Rcpp::IntegerVector SLOT, Rcpp::IntegerVector ITS, Rcpp::IntegerVector NCORES);
RcppExport SEXP _rblock_runDCSBM(SEXP KSEXP, SEXP SEEDSEXP, SEXP SLOTSEXP, SEXP ITSSEXP, SEXP NCORESSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type K(KSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type SEED(SEEDSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type SLOT(SLOTSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type ITS(ITSSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type NCORES(NCORESSEXP);
    runDCSBM(K, SEED, SLOT, ITS, NCORES);
    return R_NilValue;
END_RCPP
}
// fitParams
Rcpp::List fitParams();
RcppExport SEXP _rblock_fitParams() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(fitParams());
    return rcpp_result_gen;
END_RCPP
}
// getVertexKProbs
Rcpp::List getVertexKProbs();
RcppExport SEXP _rblock_getVertexKProbs() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(getVertexKProbs());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rblock_bernstein_poly_01_test2", (DL_FUNC) &_rblock_bernstein_poly_01_test2, 0},
    {"_rblock_resetGraph", (DL_FUNC) &_rblock_resetGraph, 0},
    {"_rblock_resetModel", (DL_FUNC) &_rblock_resetModel, 0},
    {"_rblock_deleteGraph", (DL_FUNC) &_rblock_deleteGraph, 0},
    {"_rblock_deleteModel", (DL_FUNC) &_rblock_deleteModel, 0},
    {"_rblock_print", (DL_FUNC) &_rblock_print, 1},
    {"_rblock_loadGraph", (DL_FUNC) &_rblock_loadGraph, 3},
    {"_rblock_printGraph", (DL_FUNC) &_rblock_printGraph, 0},
    {"_rblock_loadMetaData", (DL_FUNC) &_rblock_loadMetaData, 2},
    {"_rblock_runDCSBM", (DL_FUNC) &_rblock_runDCSBM, 5},
    {"_rblock_fitParams", (DL_FUNC) &_rblock_fitParams, 0},
    {"_rblock_getVertexKProbs", (DL_FUNC) &_rblock_getVertexKProbs, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_rblock(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
