# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bernstein_poly_01_test2 <- function() {
    invisible(.Call('_rblock_bernstein_poly_01_test2', PACKAGE = 'rblock'))
}

resetGraph <- function() {
    invisible(.Call('_rblock_resetGraph', PACKAGE = 'rblock'))
}

resetModel <- function() {
    invisible(.Call('_rblock_resetModel', PACKAGE = 'rblock'))
}

deleteGraph <- function() {
    invisible(.Call('_rblock_deleteGraph', PACKAGE = 'rblock'))
}

deleteModel <- function() {
    invisible(.Call('_rblock_deleteModel', PACKAGE = 'rblock'))
}

loadGraph <- function(DF, names = 1L) {
    invisible(.Call('_rblock_loadGraph', PACKAGE = 'rblock', DF, names))
}

printGraph <- function() {
    invisible(.Call('_rblock_printGraph', PACKAGE = 'rblock'))
}

loadMetaData <- function(DF) {
    invisible(.Call('_rblock_loadMetaData', PACKAGE = 'rblock', DF))
}

runDCSBM <- function(K = 0L) {
    invisible(.Call('_rblock_runDCSBM', PACKAGE = 'rblock', K))
}

getVertexKProbs <- function() {
    .Call('_rblock_getVertexKProbs', PACKAGE = 'rblock')
}

